//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thuviensachcaocap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chapter()
        {
            this.Comments = new HashSet<Comment>();
            this.ReadingProgresses = new HashSet<ReadingProgress>();
        }
    
        public int ChapterID { get; set; }
        public int BookID { get; set; }
        public Nullable<int> ChapterNumber { get; set; }
        public string ChapterTitle { get; set; }
        public string Content { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingProgress> ReadingProgresses { get; set; }
    }
}
